/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Arwil
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jbusuPrinc = new javax.swing.JButton();
        jbprtPrinc = new javax.swing.JButton();
        jbestPrinc = new javax.swing.JButton();
        jbsobrePrinc = new javax.swing.JButton();
        jbsairPrinc = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmmenuPrinc = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());
        getContentPane().add(jPanel1);

        jbusuPrinc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/botao/icons8-usuário-100.png"))); // NOI18N
        jbusuPrinc.setText("Usuário");
        getContentPane().add(jbusuPrinc);

        jbprtPrinc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/botao/icons8-produto-100.png"))); // NOI18N
        jbprtPrinc.setText("Produto");
        jbprtPrinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbprtPrincActionPerformed(evt);
            }
        });
        getContentPane().add(jbprtPrinc);

        jbestPrinc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/botao/icons8-armazém-80.png"))); // NOI18N
        jbestPrinc.setText("Estoque");
        jbestPrinc.setMaximumSize(new java.awt.Dimension(177, 107));
        jbestPrinc.setMinimumSize(new java.awt.Dimension(177, 107));
        jbestPrinc.setName(""); // NOI18N
        jbestPrinc.setPreferredSize(new java.awt.Dimension(177, 107));
        jbestPrinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbestPrincActionPerformed(evt);
            }
        });
        getContentPane().add(jbestPrinc);

        jbsobrePrinc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/botao/icons8-informações-100.png"))); // NOI18N
        jbsobrePrinc.setText("Sobre");
        getContentPane().add(jbsobrePrinc);

        jbsairPrinc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/botao/icons8-sair-100.png"))); // NOI18N
        jbsairPrinc.setText("Saír");
        jbsairPrinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsairPrincActionPerformed(evt);
            }
        });
        getContentPane().add(jbsairPrinc);

        jmmenuPrinc.setText("Arquivos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("Usuario");
        jmmenuPrinc.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem2.setText("Produto");
        jmmenuPrinc.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem3.setText("Estoque");
        jmmenuPrinc.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem4.setText("Sair");
        jmmenuPrinc.add(jMenuItem4);

        jMenuBar1.add(jmmenuPrinc);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbsairPrincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsairPrincActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbsairPrincActionPerformed

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentMoved

    private void jbestPrincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbestPrincActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbestPrincActionPerformed

    private void jbprtPrincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbprtPrincActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbprtPrincActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbestPrinc;
    private javax.swing.JButton jbprtPrinc;
    private javax.swing.JButton jbsairPrinc;
    private javax.swing.JButton jbsobrePrinc;
    private javax.swing.JButton jbusuPrinc;
    private javax.swing.JMenu jmmenuPrinc;
    // End of variables declaration//GEN-END:variables
}
